version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - ./cassandra-data:/var/lib/cassandra
      - ./cql-scripts:/fotc_database_objects
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server"]

  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
     
volumes:
  cassandra-data:
  cql-scripts:
